PA-4662 | Onboard to devops-pipeline and create Service Image
acquia/devops-blackbox-exporter pull request #1
Opened 2024-11-11 10:52 UTC by aniketasalkar

**Motivation**

Onboard to devops-pipeline and create Service Image

**Proposed changes**
Add pipeline.yaml and Dockerfile.ci

**Alternatives considered**

**Testing steps**

2024-11-12 13:10 UTC, goutamjaiswal reviewed
Just minor suggestions

2024-11-12 13:10 UTC, goutamjaiswal commented on Dockerfile
> +ARG OS
Donot change it. Although you are passing ARG from pipeline.yaml. It will already override it

2024-11-12 13:10 UTC, goutamjaiswal commented on Dockerfile
> +ARG ARCH
Donot change it. Although you are passing ARG from pipeline.yaml. It will already override it

2024-11-12 13:11 UTC, goutamjaiswal commented on .acquia/Dockerfile.ci
> +ARG ARCH
Also I can't this ARG ae used anywhere in Dockerfile.ci

2024-11-12 13:35 UTC, aniketasalkar commented on .acquia/Dockerfile.ci
> +ARG ARCH
Yes, we are not using this. I have removed them.

2024-11-12 13:36 UTC, aniketasalkar commented on Dockerfile
> +ARG ARCH
Kept Dockerfile as is from from the source repo.

2024-11-13 07:07 UTC, amanjoshicodes requested changes
Did we do any updates in the image? How were the vulnerabilities resolved?

cc: @goutamjaiswal , @AbhishekRatnawat , @SaranshIam

2024-11-13 07:07 UTC, amanjoshicodes commented on .acquia/pipeline.env
> +OS=linux
Newline at EOF

2024-11-13 07:07 UTC, amanjoshicodes commented on .acquia/pipeline.yaml
> +  ignore_failures: false
Newline at EOF

2024-11-13 07:07 UTC, amanjoshicodes commented on .acquia/Dockerfile.ci
> +ARG BASE_IMAGE=quay.io/prometheus/golang-builder:1.23-base
Use REPO_LOCATION

2024-11-13 07:07 UTC, amanjoshicodes commented on .acquia/pipeline.yaml
> +  context: "."
Add cache_from

2024-11-13 07:07 UTC, amanjoshicodes commented on .acquia/pipeline.yaml
> +      build_args:
Add cache_from

2024-11-13 07:29 UTC, aniketasalkar commented
> Did we do any updates in the image? How were the vulnerabilities resolved?
> 
> cc: @goutamjaiswal , @AbhishekRatnawat , @SaranshIam

We didn't update anything in the image. I guess it resolved from source itself.

2024-11-13 10:48 UTC, AbhishekRatnawat requested changes

2024-11-13 10:54 UTC, AbhishekRatnawat commented on .acquia/pipeline.yaml
> +  ignore_failures: false
Leave it, tag job will promote the image to prod and we will always image tag as git tag in sre-blackbox.

2024-11-13 12:30 UTC, goutamjaiswal commented on .acquia/Dockerfile.ci
> +ARG BASE_IMAGE=golang:1.23
```suggestion
ARG BASE_IMAGE=devops-blackbox-exporter/prometheus/golang-builder:1.23-base
```

2024-11-13 12:39 UTC, aniketasalkar commented on .acquia/pipeline.yaml
> +  ignore_failures: false
Updated.

2024-11-13 12:39 UTC, aniketasalkar commented on .acquia/pipeline.env
> +OS=linux
Updated.

2024-11-13 12:39 UTC, aniketasalkar commented on .acquia/pipeline.yaml
> +  context: "."
Updated.

2024-11-13 12:57 UTC, goutamjaiswal approved these changes

2024-11-13 12:57 UTC, goutamjaiswal approved these changes
LGTM

2024-11-14 06:32 UTC, SaranshIam commented on .acquia/Dockerfile.ci
> +ARG BASE_IMAGE=devops-blackbox-exporter/prometheus/golang-builder:1.23-base
You can pass BASE_IMAGE as part of build_args and use it here.

2024-11-14 07:25 UTC, aniketasalkar commented on .acquia/Dockerfile.ci
> +ARG BASE_IMAGE=devops-blackbox-exporter/prometheus/golang-builder:1.23-base
Updated it.

2024-11-14 13:13 UTC, amanjoshicodes approved these changes
LGTM

2024-11-14 13:13 UTC, merged